### ISSUE TITLE
Got quite strange result even on training data!! 

### ISSUE THREAD

**Issue by CeciliaPYY** [xuebinqin/U-2-Net#137]
First, is the results, which seems the net did't infer at all.

![image](https://user-images.githubusercontent.com/30582437/103067916-f931e480-45f6-11eb-8d48-13ffdbc24eee.png)

Hello, I trained U2Net on DUTS-TR with horizontal flipped augmentation which resulting about 2w images and trained it, the loss degrades like the following pics,
![image](https://user-images.githubusercontent.com/30582437/103067319-955aec00-45f5-11eb-86d2-4b097706a4b0.png)
However when tested on  DUTS-TE, before which I loaded the model use torch.load(checkpoint_dir, False), where False is to avoid the issue https://github.com/NathanUA/U-2-Net/issues/98. I check my pytorch version is 1.4.0.
So may be there is some insights about what's going on with the model I trained.
ps, I also check my training data, which is no doubt no problem.
![image](https://user-images.githubusercontent.com/30582437/103067534-17e3ab80-45f6-11eb-95bd-3d4afa38cf4a.png)

I think may be it's about the torch.load function, but cannot figure out the fix method.
![image](https://user-images.githubusercontent.com/30582437/103067629-4f525800-45f6-11eb-8a56-2fcbe18fc053.png)
![image](https://user-images.githubusercontent.com/30582437/103067652-5b3e1a00-45f6-11eb-919b-9f66a3d60642.png)

Double check the difference between my testing env and training env, which are definitely the same.
![image](https://user-images.githubusercontent.com/30582437/103067819-c12aa180-45f6-11eb-9f77-1524b7db890e.png)

However, the model you provided is good, which can be loaded successfully.

**Comment by CeciliaPYY** [comment]
fix by remove 'module.' from keys of state_dict, caused trained by multi-gpus.
![image](https://user-images.githubusercontent.com/30582437/103165260-7efc9c80-4850-11eb-9bd5-db44db81a201.png)

**Comment by cmdrootaccess** [comment]
hello @CeciliaPYY , are you trying to resume training from the current U2NET model ?

**Comment by CeciliaPYY** [comment]
> hello @CeciliaPYY , are you trying to resume training from the current U2NET model ?

Not now, but maybe I will, cause I find u-2-net takes too much time to train.

**Comment by seekingdeep** [comment]
@CeciliaPYY hi,
how were you able to train, i keep getting `num_samples should be a positive integer value, but got num_samples=0`
i even created a new pull request #154 to select the folders and model type.
but still getting the error

```
(unet) home@home-lnx:~/programs/U-2-Net$ python train.py --input_images ./train_data/image --input_masks ./train_data/mask --model_name u2net
/home/home/anaconda3/envs/unet/lib/python3.7/site-packages/torch/nn/_reduction.py:44: UserWarning: size_average and reduce args will be deprecated, please use reduction='mean' instead.
  warnings.warn(warning.format(ret))
---
train images:  0
train labels:  0
---
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    salobj_dataloader = DataLoader(salobj_dataset, batch_size=batch_size_train, shuffle=True, num_workers=1)
  File "/home/home/anaconda3/envs/unet/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 262, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/home/home/anaconda3/envs/unet/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 104, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0
```
