### ISSUE TITLE
Details about metricx

### ISSUE THREAD

**Issue by CheeseInTrap** [xuebinqin/U-2-Net#172]
Hi, would you like to share your code used to evaluate? I am confused about the implementation of F-measure and MAE, should I threshold probability map with 0.5 or vary the thresholds?

**Comment by xuebinqin** [comment]
Lease refer to our evaluation tool: https://github.com/xuebinqin/Binary-Segmentation-Evaluation-Tool

**Comment by CheeseInTrap** [comment]
Thanks a lot
