### ISSUE TITLE
TensorRT problems

### ISSUE THREAD

**Issue by nash-min-debug** [xuebinqin/U-2-Net#179]
Thanks for your awesome job. I use u2net to train my own dataset and get a good result.  When I try to transform the .pth file to onnx file, generating a trt file, there is no problem. However, I try to use the trt engine to do inference, a fetal error happened. The outputs are nan. Debug results show in pictures. I have tried many methods to solve this problem, but it seems useless.
![1](https://user-images.githubusercontent.com/56398622/111281294-be7c9d00-8677-11eb-82e8-6db507ef62c5.png)

Sorry, I found the binding shape was wrong

**Comment by maqiujie** [comment]
hi，when I try to transform the onnx file to trt filie，threr is a problem. Excuse me, how did you realize it?
 
Assertion faided: scales.is_weights() &&"Resize scales must be an initializer!"

**Comment by NingNanXin** [comment]
> 
1. check your input shape and output shape
2. check your onnx export is correct, use netron to visualize
3. check your model's architecture, some operations may not be supported by tentorrt
4. use the latest version tensorrt, many problems will be solved
May these suggestions will be helpful for you.
