### ISSUE TITLE
Apply U2Net to my flutter app

### ISSUE THREAD

**Issue by quyvsquy** [xuebinqin/U-2-Net#200]
Thank you, 
I have applied U2Net to determine the background-foreground for the Style Transfer problem.
Link app: https://play.google.com/store/apps/details?id=com.quyvsquy.arttransfer

**Comment by xuebinqin** [comment]
Hi, Dang, 

Just have time to update your app in the readme. https://github.com/xuebinqin/U-2-Net/blob/master/README.md.
Please feel free to give any comments or suggestions. 

Thanks again for your awesome works.

**Comment by sadaqatdev** [comment]
@quyvsquy thanks for sharing the work 
can you tell me how you are using this in flutter app , what to use with pytourch or TF lite for background remover app

**Comment by quyvsquy** [comment]
Hi @sadaqatdev,
I my fullter app just a client to show result from the server,
All task like find similar, background remove, style stransfer is processing in server.

**Comment by sadaqatdev** [comment]
Ant idea about directly use in mobile device like playTourch or using tenser flow or pytourch
