### ISSUE TITLE
why you use custom randomcrop instead of torchvision.transforms.RandomCrop ?

### ISSUE THREAD

**Issue by whcjb** [xuebinqin/U-2-Net#213]
hello, i read your realease code, found that in the data preprocess, you use custom randomcrop, i wonder why not use the torchvision's, is there different?

**Comment by xuebinqin** [comment]
At the beginning, we tried many different augmentation ideas, which didn't work. So we just keep the using the function we built. There shouldn't be that much differences.

**Comment by whcjb** [comment]
ok, thanks a lot.
