### ISSUE TITLE
Inference model with MNN framework

### ISSUE THREAD

**Issue by AnhPC03** [xuebinqin/U-2-Net#343]
Hello everyone,
I converted Pytorch to Onnx model and inferenced successfully. I also converted Onnx to MNN successfully too, but when I ran inference on MNN, it was not correct. It only had half above of image, I searched everywhere but still could not find the half below.
Have you worked with MNN and U2Net, please help me.
Thank you

**Comment by RUIXUEZHAOFENGNIAN** [comment]
hi, could u provide the U2Netp  onnx model?
