### ISSUE TITLE
Continue training, train my own model with U-2-Net, in between due to some reasons the training was interrupted or I want to strengthen an existing model, what should I do? Can you provide a 'Continue-training.py'?

### ISSUE THREAD

**Issue by panpengfei21** [xuebinqin/U-2-Net#358]
Continue training, train my model with U-2-Net, in between due to some reasons the training was interrupted or I want to strengthen an existing model, what should I do? Can you provide a 'Continue-training.py'?

**Comment by DonkeySmall** [comment]
```
u2net_train.py

if torch.cuda.is_available():
        net.load_state_dict(torch.load(your model path))
        net.cuda()
```

**Comment by panpengfei21** [comment]
> 

thank you, I will try.

**Comment by panpengfei21** [comment]
> ```
> u2net_train.py
> 
> if torch.cuda.is_available():
>         net.load_state_dict(torch.load(your model path))
>         net.cuda()
> ```

My computer is MacBook Pro, so `torch.cuda.is_available()` is false.
I change your code like this:
```
    checkpoint = torch.load("/xxx/xxx/xxx.pth", map_location='cpu')
    net.load_state_dict(checkpoint)
    if torch.cuda.is_available():
        net.cuda()
```

Is it OK?

**Comment by DonkeySmall** [comment]
double slash "//xxx//xxx//xxx.pth"

should work
