### ISSUE TITLE
u2net_train.py returning ValueError

### ISSUE THREAD

**Issue by rajm-dv** [xuebinqin/U-2-Net#376]
Can anyone help me to fix this:
I'm trying to train u2net with DUTS dataset for my personal python project (removing complex background from images)
u2net_test.py run successfully with DUTS dataset but u2net_train.py is returning error like this-

![298676491-3ac92c00-ad77-42a5-b823-2512937fa52d](https://github.com/xuebinqin/U-2-Net/assets/108714991/e519a978-ec7a-400a-87e4-dd4189fac39d)

I am using python 3.9 for this project.
I'm a beginner in python.. It was very helpful for me if anyone teach me step by step how to trained u2net with custom dataset like DUTS.. I try almost very thing I can 😢.

**Comment by Muzi010** [comment]
你解决了么？我和你遇见了相同的问题，能否讨论一下
